name: kmart-demo

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET env for the class library Kmart.Code.Challenge
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies by pulling the nuget packages
      run: dotnet restore
    - name: Build the class library Kmart.Code.Challenge
      run: dotnet build --no-restore
    - name: Run the given 11 test cases
      run: dotnet test --no-build --verbosity normal
